import { useState } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { NearbyDoctors } from "@/components/health/NearbyDoctors";
import { HealthDisclaimer } from "@/components/health/HealthDisclaimer";
import { MenopauseAssessmentForm } from "@/components/health/MenopauseAssessmentForm";
import { MenopauseResultsDisplay } from "@/components/health/MenopauseResultsDisplay";
import { EducationCard } from "@/components/health/EducationCard";

import { 
  Thermometer, 
  ArrowRight,
  Sparkles,
  ArrowLeft,
  Heart,
  Flame,
  Moon,
  Frown,
  Bone,
  Stethoscope,
  Clock,
  Brain,
  Loader2
} from "lucide-react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import { predictMenopauseFromAPI, MenopauseInputData, MenopauseResult, MLPredictionMeta } from "@/lib/ml-predictions";

type Step = "education" | "assessment" | "results" | "doctors";

const stepLabels = ["Learn", "Assess", "Results", "Consult"];

const MenopauseModule = () => {
  const { user } = useAuth();
  const [currentStep, setCurrentStep] = useState<Step>("education");
  const [menopauseResult, setMenopauseResult] = useState<MenopauseResult | null>(null);
  const [predictionMeta, setPredictionMeta] = useState<MLPredictionMeta | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleAssessmentSubmit = async (data: MenopauseInputData) => {
    setAnalyzing(true);
    try {
      const { _meta, ...result } = await predictMenopauseFromAPI(data);
      setMenopauseResult(result);
      setPredictionMeta(_meta);
      setCurrentStep("results");

      if (_meta.usedAPI) {
        toast({
          title: "ML Model Analysis Complete",
          description: "Results generated by our trained ML model. 🧠",
        });
      } else {
        toast({
          title: "Local Analysis Complete",
          description: _meta.error || "Used built-in scoring logic.",
        });
      }

      if (user) {
        setSaving(true);
        try {
          const { error } = await supabase.from("health_assessments").insert({
            user_id: user.id,
            assessment_type: _meta.usedAPI ? "menopause_ml_api" : "menopause_ml_local",
            risk_score: result.riskPercentage,
            risk_category: result.stage === 'Pre-Menopause' ? 'low' : result.stage === 'Peri-Menopause' ? 'medium' : 'high',
            responses: data as any,
            recommendations: result.recommendations as any,
          });

          if (error) throw error;
          toast({ 
            title: "Assessment saved", 
            description: "Your menopause assessment results have been saved." 
          });
        } catch (error) {
          console.error("Failed to save assessment:", error);
          toast({
            title: "Error",
            description: "Failed to save assessment. Results are still displayed.",
            variant: "destructive",
          });
        } finally {
          setSaving(false);
        }
      }
    } catch (error) {
      console.error("Assessment failed:", error);
      toast({
        title: "Error",
        description: "Assessment failed. Please try again.",
        variant: "destructive",
      });
    } finally {
      setAnalyzing(false);
    }
  };

  const restartAssessment = () => {
    setCurrentStep("education");
    setMenopauseResult(null);
  };

  const currentStepIndex = ["education", "assessment", "results", "doctors"].indexOf(currentStep);

  const menopauseStages = [
    {
      title: "Pre-Menopause",
      description: "Regular reproductive years with normal menstrual cycles",
      icon: <Heart className="w-5 h-5" />,
      isCompleted: true,
    },
    {
      title: "Peri-Menopause",
      description: "Transition phase - irregular periods, symptoms begin (can last 4-8 years)",
      icon: <Clock className="w-5 h-5" />,
      isActive: false,
    },
    {
      title: "Menopause",
      description: "12 consecutive months without menstruation (average age: 51)",
      icon: <Flame className="w-5 h-5" />,
      isActive: false,
    },
    {
      title: "Post-Menopause",
      description: "Years after menopause - focus on long-term health management",
      icon: <Sparkles className="w-5 h-5" />,
      isActive: false,
    },
  ];

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Improved Progress Indicator */}
          <div className="mb-10">
            <div className="flex items-center justify-between mb-2">
              {stepLabels.map((label, i) => (
                <div key={label} className="flex flex-col items-center flex-1">
                  <motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: currentStepIndex === i ? 1.1 : 1 }}
                    className={`w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 ${
                      currentStepIndex === i 
                        ? "bg-teal text-teal-foreground shadow-lg shadow-teal/30" 
                        : currentStepIndex > i
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {currentStepIndex > i ? "✓" : i + 1}
                  </motion.div>
                  <span className={`text-xs mt-2 font-medium ${
                    currentStepIndex === i ? "text-teal" : "text-muted-foreground"
                  }`}>
                    {label}
                  </span>
                </div>
              ))}
            </div>
            <div className="relative h-1 bg-muted rounded-full mt-4">
              <motion.div
                initial={{ width: "0%" }}
                animate={{ width: `${(currentStepIndex / 3) * 100}%` }}
                className="absolute h-full bg-gradient-to-r from-teal to-primary rounded-full"
                transition={{ duration: 0.5 }}
              />
            </div>
          </div>

          {/* Education Step */}
          {currentStep === "education" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-8"
            >
              {/* Hero Section */}
              <div className="text-center">
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", duration: 0.5 }}
                  className="w-24 h-24 rounded-3xl bg-gradient-to-br from-teal/30 to-primary/30 flex items-center justify-center mx-auto mb-6"
                >
                  <Thermometer className="w-12 h-12 text-teal" />
                </motion.div>
                <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
                  Understanding Menopause
                </h1>
                <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                  A natural transition that every woman experiences. Learn about the stages, 
                  symptoms, and how to manage this important life phase.
                </p>
              </div>

              {/* Quick Stats */}
              <div className="grid grid-cols-3 gap-4">
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.1 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-teal">45-55</div>
                  <div className="text-xs text-muted-foreground">Typical Age Range</div>
                </motion.div>
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.2 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-primary">51</div>
                  <div className="text-xs text-muted-foreground">Average Age</div>
                </motion.div>
                <motion.div
                  initial={{ y: 20, opacity: 0 }}
                  animate={{ y: 0, opacity: 1 }}
                  transition={{ delay: 0.3 }}
                  className="glass-card rounded-xl p-4 text-center"
                >
                  <div className="text-3xl font-bold text-accent">4-8</div>
                  <div className="text-xs text-muted-foreground">Years Transition</div>
                </motion.div>
              </div>

              {/* Visual Timeline of Stages */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="glass-card rounded-2xl p-6"
              >
                <h3 className="font-heading text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
                  <Clock className="w-5 h-5 text-teal" />
                  Stages of Menopause
                </h3>
                <div className="space-y-4">
                  {menopauseStages.map((stage, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: index * 0.1 }}
                      className={`flex items-start gap-4 p-4 rounded-xl ${
                        stage.isCompleted ? "bg-teal/10 border border-teal/30" :
                        stage.isActive ? "bg-primary/10 border border-primary/30" :
                        "bg-muted/50"
                      }`}
                    >
                      <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${
                        stage.isCompleted ? "bg-teal text-teal-foreground" :
                        stage.isActive ? "bg-primary text-primary-foreground" :
                        "bg-muted text-muted-foreground"
                      }`}>
                        {stage.icon}
                      </div>
                      <div>
                        <h4 className="font-medium text-foreground">{stage.title}</h4>
                        <p className="text-sm text-muted-foreground">{stage.description}</p>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>

              {/* Symptoms Cards */}
              <div className="space-y-4">
                <EducationCard
                  icon={Flame}
                  title="Hot Flashes & Night Sweats"
                  description="Sudden feelings of warmth, often most intense over face, neck, and chest. Can cause sweating and sleep disruption."
                  color="accent"
                  delay={0.1}
                />
                
                <EducationCard
                  icon={Moon}
                  title="Sleep & Mood Changes"
                  description=""
                  items={[
                    "Difficulty falling or staying asleep",
                    "Mood swings and irritability",
                    "Anxiety or feelings of sadness",
                    "Memory and concentration changes"
                  ]}
                  color="primary"
                  delay={0.2}
                />
                
                <EducationCard
                  icon={Bone}
                  title="Physical Changes"
                  description=""
                  items={[
                    "Vaginal dryness and discomfort",
                    "Changes in skin and hair",
                    "Joint and muscle pain",
                    "Weight changes, especially around waist"
                  ]}
                  color="teal"
                  delay={0.3}
                />
              </div>

              <HealthDisclaimer />

              <div className="text-center">
                <Button size="lg" onClick={() => setCurrentStep("assessment")} className="group text-lg px-8 bg-teal hover:bg-teal/90">
                  <Heart className="w-5 h-5 mr-2" />
                  Start Assessment
                  <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </div>
            </motion.div>
          )}

          {/* Assessment Step */}
          {currentStep === "assessment" && !analyzing && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
            >
              <div className="text-center mb-8">
                <h1 className="font-heading text-2xl md:text-3xl font-bold text-foreground mb-2">
                  Menopause Stage Assessment
                </h1>
                <p className="text-muted-foreground">
                  Answer honestly for accurate results • Takes ~3 minutes
                </p>
              </div>

              <MenopauseAssessmentForm onSubmit={handleAssessmentSubmit} />

              <div className="text-center mt-6">
                <Button variant="ghost" onClick={() => setCurrentStep("education")}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Education
                </Button>
              </div>
            </motion.div>
          )}

          {/* Analyzing Overlay */}
          {analyzing && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center justify-center py-20"
            >
              <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-teal/30 to-primary/30 flex items-center justify-center mb-6">
                <Loader2 className="w-10 h-10 text-teal animate-spin" />
              </div>
              <h2 className="font-heading text-2xl font-bold text-foreground mb-2">
                Analyzing with ML Model...
              </h2>
              <p className="text-muted-foreground text-sm max-w-sm text-center">
                Running your data through our trained menopause stage classifier
              </p>
              <div className="flex gap-1 mt-6">
                {[0, 1, 2].map(i => (
                  <motion.div
                    key={i}
                    className="w-3 h-3 rounded-full bg-teal"
                    animate={{ scale: [1, 1.3, 1], opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                  />
                ))}
              </div>
            </motion.div>
          )}

          {/* Results Step */}
          {currentStep === "results" && menopauseResult && (
            <div>
              {predictionMeta && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`mb-4 flex items-center justify-center gap-2 px-4 py-2 rounded-full text-xs font-medium w-fit mx-auto ${
                    predictionMeta.usedAPI 
                      ? "bg-teal/20 text-teal border border-teal/30" 
                      : "bg-muted text-muted-foreground border border-border"
                  }`}
                >
                  <Brain className="w-3.5 h-3.5" />
                  {predictionMeta.usedAPI ? "🧠 ML Model Prediction" : "📊 Local Analysis (Fallback)"}
                </motion.div>
              )}
              <MenopauseResultsDisplay 
                result={menopauseResult}
                onFindDoctors={() => setCurrentStep("doctors")}
                onRestart={restartAssessment}
              />
            </div>
          )}

          {/* Doctors Step */}
          {currentStep === "doctors" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
            >
              <div className="text-center mb-10">
                <div className="w-16 h-16 rounded-2xl bg-teal/20 flex items-center justify-center mx-auto mb-4">
                  <Stethoscope className="w-8 h-8 text-teal" />
                </div>
                <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-4">
                  Find Menopause Specialists
                </h1>
                <p className="text-muted-foreground">
                  Connect with qualified gynecologists and menopause specialists
                </p>
              </div>

              <NearbyDoctors specialty="Gynecologist" />

              <div className="flex flex-col sm:flex-row gap-4 justify-center mt-10">
                <Button variant="outline" onClick={() => setCurrentStep("results")}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Results
                </Button>
                <Button variant="outline" onClick={restartAssessment}>
                  Take Assessment Again
                </Button>
              </div>
            </motion.div>
          )}
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default MenopauseModule;
