import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Button } from "@/components/ui/button";
import { HealthDisclaimer } from "@/components/health/HealthDisclaimer";
import { PCOSAssessmentForm } from "@/components/health/PCOSAssessmentForm";
import { PCOSResultsDisplay } from "@/components/health/PCOSResultsDisplay";
import { EducationCard } from "@/components/health/EducationCard";

import { 
  Activity, 
  ArrowRight,
  Sparkles,
  ArrowLeft,
  AlertCircle,
  Heart,
  Scale,
  Brain,
  Loader2,
  TestTube,
  Microscope,
  ShieldCheck,
  FileText,
  CheckCircle2
} from "lucide-react";
import { motion } from "framer-motion";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { toast } from "@/hooks/use-toast";
import { predictPCOSFromAPI, PCOSInputData, PCOSResult, MLPredictionMeta } from "@/lib/ml-predictions";

type Step = "education" | "assessment" | "results";

const stepLabels = ["Learn", "Assess", "Results"];

const PCOSModule = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [currentStep, setCurrentStep] = useState<Step>("education");
  const [pcosResult, setPcosResult] = useState<PCOSResult | null>(null);
  const [predictionMeta, setPredictionMeta] = useState<MLPredictionMeta | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [saving, setSaving] = useState(false);

  const handleAssessmentSubmit = async (data: PCOSInputData) => {
    setAnalyzing(true);
    try {
      const { _meta, ...result } = await predictPCOSFromAPI(data);
      setPcosResult(result);
      setPredictionMeta(_meta);
      setCurrentStep("results");

      if (_meta.usedAPI) {
        toast({
          title: "ML Model Analysis Complete",
          description: "Results generated by our trained ML model. 🧠",
        });
      } else {
        toast({
          title: "Local Analysis Complete",
          description: _meta.error || "Used built-in scoring logic.",
        });
      }

      if (user) {
        setSaving(true);
        try {
          const { error } = await supabase.from("health_assessments").insert({
            user_id: user.id,
            assessment_type: _meta.usedAPI ? "pcos_ml_api" : "pcos_ml_local",
            risk_score: result.riskPercentage,
            risk_category: result.severity === 'none' ? 'low' : result.severity,
            responses: data as any,
            recommendations: result.recommendations as any,
          });

          if (error) throw error;
          toast({ 
            title: "Assessment saved", 
            description: "Your PCOS assessment results have been saved." 
          });
        } catch (error) {
          console.error("Failed to save assessment:", error);
          toast({
            title: "Error",
            description: "Failed to save assessment. Results are still displayed.",
            variant: "destructive",
          });
        } finally {
          setSaving(false);
        }
      }
    } catch (error) {
      console.error("Assessment failed:", error);
      toast({
        title: "Error",
        description: "Assessment failed. Please try again.",
        variant: "destructive",
      });
    } finally {
      setAnalyzing(false);
    }
  };

  const restartAssessment = () => {
    setCurrentStep("education");
    setPcosResult(null);
  };

  const currentStepIndex = ["education", "assessment", "results"].indexOf(currentStep);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-24 pb-16">
        <div className="container mx-auto px-4 max-w-4xl">
          {/* Progress Indicator */}
          <div className="mb-10">
            <div className="flex items-center justify-between mb-2">
              {stepLabels.map((label, i) => (
                <div key={label} className="flex flex-col items-center flex-1">
                  <motion.div
                    initial={{ scale: 0.8 }}
                    animate={{ scale: currentStepIndex === i ? 1.1 : 1 }}
                    className={`w-10 h-10 md:w-12 md:h-12 rounded-full flex items-center justify-center text-sm font-bold transition-all duration-300 ${
                      currentStepIndex === i 
                        ? "bg-accent text-accent-foreground shadow-lg shadow-accent/30" 
                        : currentStepIndex > i
                        ? "bg-teal text-teal-foreground"
                        : "bg-muted text-muted-foreground"
                    }`}
                  >
                    {currentStepIndex > i ? "✓" : i + 1}
                  </motion.div>
                  <span className={`text-xs mt-2 font-medium ${
                    currentStepIndex === i ? "text-accent" : "text-muted-foreground"
                  }`}>
                    {label}
                  </span>
                </div>
              ))}
            </div>
            <div className="relative h-1 bg-muted rounded-full mt-4">
              <motion.div
                initial={{ width: "0%" }}
                animate={{ width: `${(currentStepIndex / 2) * 100}%` }}
                className="absolute h-full bg-gradient-to-r from-accent to-teal rounded-full"
                transition={{ duration: 0.5 }}
              />
            </div>
          </div>

          {/* Education Step - Clinical Version */}
          {currentStep === "education" && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="space-y-8"
            >
              {/* Hero Section */}
              <div className="text-center">
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", duration: 0.5 }}
                  className="w-24 h-24 rounded-3xl bg-gradient-to-br from-accent/30 to-primary/30 flex items-center justify-center mx-auto mb-6"
                >
                  <Activity className="w-12 h-12 text-accent" />
                </motion.div>
                <h1 className="font-heading text-3xl md:text-4xl font-bold text-foreground mb-3">
                  🌸 PCOS Clinical Risk Assessment
                </h1>
                <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
                  Accurate AI-Based Hormonal Evaluation
                </p>
                <p className="text-muted-foreground text-sm max-w-xl mx-auto mt-3">
                  This assessment provides a clinically informed PCOS risk evaluation using medical data and symptoms. 
                  For accurate prediction, <span className="font-semibold text-foreground">correct clinical test values are required.</span>
                </p>
              </div>

              {/* How NaariCare AI Works */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="glass-card rounded-2xl p-6 border border-accent/30"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-accent/20 flex items-center justify-center">
                    <Brain className="w-5 h-5 text-accent" />
                  </div>
                  <h3 className="font-heading text-lg font-semibold text-foreground">🧠 How NaariCare AI Works</h3>
                </div>
                <p className="text-sm text-muted-foreground mb-4">
                  NaariCare's machine learning model analyzes your data against medically validated patterns to estimate PCOS risk:
                </p>
                <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
                  {[
                    { icon: "🩸", label: "Menstrual cycle info" },
                    { icon: "⚖️", label: "Body measurements" },
                    { icon: "🌸", label: "Symptoms" },
                    { icon: "🩺", label: "Ultrasound findings" },
                    { icon: "🧪", label: "Blood hormone levels" },
                  ].map((item, i) => (
                    <motion.div
                      key={i}
                      initial={{ y: 10, opacity: 0 }}
                      animate={{ y: 0, opacity: 1 }}
                      transition={{ delay: 0.15 + i * 0.05 }}
                      className="text-center p-3 rounded-xl bg-muted/50"
                    >
                      <div className="text-2xl mb-1">{item.icon}</div>
                      <div className="text-xs text-muted-foreground">{item.label}</div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>

              {/* Information Required */}
              <div className="space-y-4">
                <h3 className="font-heading text-lg font-semibold text-foreground px-1">
                  📋 Information Required Before You Begin
                </h3>

                <EducationCard
                  icon={Scale}
                  title="✅ Basic Health Details"
                  description=""
                  items={[
                    "Age, Height, Weight",
                    "Cycle regularity & average cycle length",
                    "Symptoms: acne, hair growth, weight gain",
                  ]}
                  color="teal"
                  delay={0.1}
                />

                <EducationCard
                  icon={Microscope}
                  title="🩺 Ultrasound Report (Required)"
                  description="From your pelvic sonography report:"
                  items={[
                    "🥚 Follicle count – Left ovary",
                    "🥚 Follicle count – Right ovary",
                    "📄 Endometrium thickness (mm)",
                  ]}
                  color="accent"
                  delay={0.2}
                />

                <EducationCard
                  icon={TestTube}
                  title="🧪 Blood Test Report (Required)"
                  description="Hormone profile blood test values:"
                  items={[
                    "LH (Luteinizing Hormone)",
                    "FSH (Follicle Stimulating Hormone)",
                    "Testosterone (Total)",
                    "Insulin (Fasting)",
                  ]}
                  color="primary"
                  delay={0.3}
                />
              </div>

              {/* Important Accuracy Notice */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.35 }}
                className="p-5 rounded-2xl bg-destructive/10 border border-destructive/20"
              >
                <div className="flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 text-destructive mt-0.5 flex-shrink-0" />
                  <div>
                    <h4 className="font-semibold text-destructive mb-2">⚠️ Important Accuracy Notice</h4>
                    <ul className="space-y-1 text-sm text-muted-foreground">
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-destructive flex-shrink-0 mt-0.5" />
                        Use official medical reports only
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-destructive flex-shrink-0 mt-0.5" />
                        Enter values exactly as written in reports
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-destructive flex-shrink-0 mt-0.5" />
                        Ensure measurements are in correct units
                      </li>
                      <li className="flex items-start gap-2">
                        <CheckCircle2 className="w-4 h-4 text-destructive flex-shrink-0 mt-0.5" />
                        If reports are unavailable, consult a gynecologist first
                      </li>
                    </ul>
                  </div>
                </div>
              </motion.div>

              {/* Why Medical Reports Are Required */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4 }}
                className="glass-card rounded-2xl p-6"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-10 h-10 rounded-lg bg-teal/20 flex items-center justify-center">
                    <ShieldCheck className="w-5 h-5 text-teal" />
                  </div>
                  <h3 className="font-heading text-lg font-semibold text-foreground">🏥 Why Medical Reports Are Required</h3>
                </div>
                <p className="text-sm text-muted-foreground mb-4">
                  PCOS diagnosis is based on clinical symptoms, ultrasound findings, and hormonal imbalance. 
                  NaariCare follows the same clinical logic to provide a data-driven risk evaluation.
                </p>
                <div className="grid grid-cols-3 gap-3">
                  {[
                    { label: "Higher accuracy", icon: "🎯" },
                    { label: "Reliable estimation", icon: "📊" },
                    { label: "Transparent AI", icon: "🔍" },
                  ].map((item, i) => (
                    <div key={i} className="text-center p-3 rounded-xl bg-teal/10">
                      <div className="text-xl mb-1">{item.icon}</div>
                      <div className="text-xs font-medium text-foreground">{item.label}</div>
                    </div>
                  ))}
                </div>
              </motion.div>

              <HealthDisclaimer />

              <div className="text-center">
                <Button size="lg" onClick={() => setCurrentStep("assessment")} className="group text-lg px-8">
                  <Sparkles className="w-5 h-5 mr-2" />
                  Start Clinical Assessment
                  <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
                </Button>
              </div>
            </motion.div>
          )}

          {/* Assessment Step */}
          {currentStep === "assessment" && !analyzing && (
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
            >
              <div className="text-center mb-8">
                <h1 className="font-heading text-2xl md:text-3xl font-bold text-foreground mb-2">
                  PCOS Clinical Risk Assessment
                </h1>
                <p className="text-muted-foreground">
                  Enter values from your medical reports • Takes ~5 minutes
                </p>
              </div>

              <PCOSAssessmentForm onSubmit={handleAssessmentSubmit} />

              <div className="text-center mt-6">
                <Button variant="ghost" onClick={() => setCurrentStep("education")}>
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Back to Information
                </Button>
              </div>
            </motion.div>
          )}

          {/* Analyzing Overlay */}
          {analyzing && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="flex flex-col items-center justify-center py-20"
            >
              <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-accent/30 to-primary/30 flex items-center justify-center mb-6">
                <Loader2 className="w-10 h-10 text-accent animate-spin" />
              </div>
              <h2 className="font-heading text-2xl font-bold text-foreground mb-2">
                Analyzing with ML Model...
              </h2>
              <p className="text-muted-foreground text-sm max-w-sm text-center">
                Running your clinical data through our trained Random Forest + XGBoost ensemble model
              </p>
              <div className="flex gap-1 mt-6">
                {[0, 1, 2].map(i => (
                  <motion.div
                    key={i}
                    className="w-3 h-3 rounded-full bg-accent"
                    animate={{ scale: [1, 1.3, 1], opacity: [0.5, 1, 0.5] }}
                    transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                  />
                ))}
              </div>
            </motion.div>
          )}

          {/* Results Step */}
          {currentStep === "results" && pcosResult && (
            <div>
              {predictionMeta && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className={`mb-4 flex items-center justify-center gap-2 px-4 py-2 rounded-full text-xs font-medium w-fit mx-auto ${
                    predictionMeta.usedAPI 
                      ? "bg-teal/20 text-teal border border-teal/30" 
                      : "bg-muted text-muted-foreground border border-border"
                  }`}
                >
                  <Brain className="w-3.5 h-3.5" />
                  {predictionMeta.usedAPI ? "🧠 ML Model Prediction" : "📊 Local Analysis (Fallback)"}
                </motion.div>
              )}
              <PCOSResultsDisplay 
                result={pcosResult}
                onFindDoctors={() => navigate("/doctors?source=assessment")}
                onRestart={restartAssessment}
              />
            </div>
          )}

        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PCOSModule;
